#!/usr/bin/env bash
# output 1-100
#fizz in multiple of 3 position
#buzz in multiple of 5 position
#fizzbuzz in multiple of both 3 & 5 position
i=1
while [ $i -le 100 ]
do
	mult3=$((i%3))
	mult5=$((i%5))
	if [ $mult3 == "0" ] && [ $mult5 == "0" ]
	then
		echo "FizzBuzz"
	elif [ $mult3 == "0" ]
	then
		echo "Fizz"
	elif [ $mult5 == "0" ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
