#!/usr/bin/env bash
# output Best School 8 times, bad luck once at position 4, and good luck once at position 8
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
