#!/usr/bin/env bash
# output 1 to 20 while bad luck from - will follow 4, 9, and 17. - is the country name
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
